apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-username: {{ "averbis" | b64enc | quote }}