apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  database-root-password: {{ randAlphaNum 15 | b64enc | quote }}
  database-password: {{ randAlphaNum 15 | b64enc | quote }}
  database-username: {{ "averbis" | b64enc | quote }}